name: Build

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout main repo
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: "temurin"
        java-version: "17"

    - name: Get latest commit hash
      id: latest_commit
      run: echo "hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Build APK
      run: |
        bash build.sh release

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: TrebleApp
        path: TrebleApp.apk

    - name: Checkout overlay repo
      uses: actions/checkout@v4
      with:
        repository: MP01Experiments/vendor_hardware_overlay
        ref: pie
        token: ${{ secrets.GITHUB_TOKEN }}
        path: vendor_hardware_overlay

    - name: Update APK
      run: |
       git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          cp TrebleApp.apk vendor_hardware_overlay/TrebleApp/app.apk
          cd vendor_hardware_overlay
          git add TrebleApp/app.apk
          git commit -m "Up TrebleApp to TrebleDroid/treble_app@${{ steps.latest_commit.outputs.hash }}" || echo "No changes to commit"
          git push origin pie
